"""empty message

Revision ID: 3e49bf38e6b4
Revises: 
Create Date: 2025-07-02 10:38:04.770084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e49bf38e6b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(length=20), nullable=False),
    sa.Column('chat_description', sa.String(length=100), nullable=True),
    sa.Column('chat_owner', sa.Integer(), nullable=False),
    sa.Column('chat_date_made', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['chat_owner'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id'),
    sa.UniqueConstraint('chat_name')
    )
    op.create_table('chat_members',
    sa.Column('chat_member_id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.Integer(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_name'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_member_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_poster', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_date_made', sa.DateTime(), nullable=False),
    sa.Column('belongs_to_chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['belongs_to_chat'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['message_poster'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chat_members')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
