"""empty message

Revision ID: 75020e2ac0b3
Revises: 
Create Date: 2025-08-03 23:33:14.863177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75020e2ac0b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avatar_url'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_name', sa.String(length=20), nullable=False),
    sa.Column('chat_description', sa.String(length=100), nullable=True),
    sa.Column('chat_owner', sa.Integer(), nullable=False),
    sa.Column('chat_date_made', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['chat_owner'], ['users.id'], name='fk_userid_chat_owner'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_name')
    )
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='fk_chatid_chatid'),
    sa.ForeignKeyConstraint(['username'], ['users.id'], name='fk_userid_username'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_poster', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_date_made', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='fk_chatid_belongs_to_chat'),
    sa.ForeignKeyConstraint(['message_poster'], ['users.id'], name='fk_userid_message_poster'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chat_members')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
